export const helperConstants = {
  THEME_CHANGE_REQUEST: "THEME_CHANGE_REQUEST",
  FETCH_LOCATION_REQUEST: "FETCH_LOCATION_REQUEST",
};

export const bannerConstants = {
  GET_HOME_CAROUSEL_BANNER_REQUEST: "GET_HOME_CAROUSEL_BANNER_REQUEST",
  GET_HOME_CAROUSEL_BANNER_FAILURE: "GET_HOME_CAROUSEL_BANNER_FAILURE",
  GET_HOME_CAROUSEL_BANNER_SUCCESS: "GET_HOME_CAROUSEL_BANNER_SUCCESS",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const signupConstants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_CLEAR: "SIGNUP_CLEAR",
};

export const categoryConstants = {
  GET_ALL_CAT_REQUEST: "GET_ALL_CAT_REQUEST",
  GET_ALL_CAT_FAILURE: "GET_ALL_CAT_FAILURE",
  GET_ALL_CAT_SUCCESS: "GET_ALL_CAT_SUCCESS",
};

export const jobsConstants = {
  GET_HOME_LOCAL_JOBS_REQUEST: "GET_HOME_LOCAL_JOBS_REQUEST",
  GET_HOME_LOCAL_JOBS_FAILURE: "GET_HOME_LOCAL_JOBS_FAILURE",
  GET_HOME_LOCAL_JOBS_SUCCESS: "GET_HOME_LOCAL_JOBS_SUCCESS",
  GET_JOBS_BY_CATEGORY_REQUEST: "GET_JOBS_BY_CATEGORY_REQUEST",
  GET_JOBS_BY_CATEGORY_FAILURE: "GET_JOBS_BY_CATEGORY_FAILURE",
  GET_JOBS_BY_CATEGORY_SUCCESS: "GET_JOBS_BY_CATEGORY_SUCCESS",
  GET_JOB_BY_ID_REQUEST: "GET_JOB_BY_ID_REQUEST",
  GET_JOB_BY_ID_FAILURE: "GET_JOB_BY_ID_FAILURE",
  GET_JOB_BY_ID_SUCCESS: "GET_JOB_BY_ID_SUCCESS",
};

export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_FAILURE: "GET_CART_FAILURE",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  DEL_CART_ITEM_REQUEST: "DEL_CART_ITEM_REQUEST",
  DEL_CART_ITEM_FAILURE: "DEL_CART_ITEM_FAILURE",
  DEL_CART_ITEM_SUCCESS: "DEL_CART_ITEM_SUCCESS",
};

export const orderConstants = {
  CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
  CREATE_ORDER_FAILURE: "CREATE_ORDER_FAILURE",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",
  GET_ORDERS_FAILURE: "GET_ORDERS_FAILURE",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
};
