export const helperConstants = {
  THEME_CHANGE_REQUEST: "THEME_CHANGE_REQUEST",
  FETCH_LOCATION_REQUEST: "FETCH_LOCATION_REQUEST",
  MARGIN_CHANGE_REQUEST: "MARGIN_CHANGE_REQUEST",
};

export const bannerConstants = {
  GET_HOME_CAROUSEL_BANNER_REQUEST: "GET_HOME_CAROUSEL_BANNER_REQUEST",
  GET_HOME_CAROUSEL_BANNER_FAILURE: "GET_HOME_CAROUSEL_BANNER_FAILURE",
  GET_HOME_CAROUSEL_BANNER_SUCCESS: "GET_HOME_CAROUSEL_BANNER_SUCCESS",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  SEND_RESET_PWD_REQUEST: "SEND_RESET_PWD_REQUEST",
  SEND_RESET_PWD_FAILURE: "SEND_RESET_PWD_FAILURE",
  SEND_RESET_PWD_SUCCESS: "SEND_RESET_PWD_SUCCESS",
  VERIFY_RESET_PWD_REQUEST: "VERIFY_RESET_PWD_REQUEST",
  VERIFY_RESET_PWD_FAILURE: "VERIFY_RESET_PWD_FAILURE",
  VERIFY_RESET_PWD_SUCCESS: "VERIFY_RESET_PWD_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  AUTH_CLEAR: "AUTH_CLEAR",
};

export const signupConstants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_CLEAR: "SIGNUP_CLEAR",
  EMAIL_OTP_VERIFY_REQUEST: "EMAIL_OTP_VERIFY_REQUEST",
  EMAIL_OTP_VERIFY_FAILURE: "EMAIL_OTP_VERIFY_FAILURE",
  EMAIL_OTP_VERIFY_SUCCESS: "EMAIL_OTP_VERIFY_SUCCESS",
  EMAIL_OTP_RESEND_REQUEST: "EMAIL_OTP_RESEND_REQUEST",
  EMAIL_OTP_RESEND_FAILURE: "EMAIL_OTP_RESEND_FAILURE",
  EMAIL_OTP_RESEND_SUCCESS: "EMAIL_OTP_RESEND_SUCCESS",
};

export const categoryConstants = {
  GET_ALL_CAT_REQUEST: "GET_ALL_CAT_REQUEST",
  GET_ALL_CAT_FAILURE: "GET_ALL_CAT_FAILURE",
  GET_ALL_CAT_SUCCESS: "GET_ALL_CAT_SUCCESS",
};

export const jobsConstants = {
  GET_HOME_LOCAL_JOBS_REQUEST: "GET_HOME_LOCAL_JOBS_REQUEST",
  GET_HOME_LOCAL_JOBS_FAILURE: "GET_HOME_LOCAL_JOBS_FAILURE",
  GET_HOME_LOCAL_JOBS_SUCCESS: "GET_HOME_LOCAL_JOBS_SUCCESS",
  GET_JOBS_BY_CATEGORY_REQUEST: "GET_JOBS_BY_CATEGORY_REQUEST",
  GET_JOBS_BY_CATEGORY_FAILURE: "GET_JOBS_BY_CATEGORY_FAILURE",
  GET_JOBS_BY_CATEGORY_SUCCESS: "GET_JOBS_BY_CATEGORY_SUCCESS",
  GET_JOB_BY_ID_REQUEST: "GET_JOB_BY_ID_REQUEST",
  GET_JOB_BY_ID_FAILURE: "GET_JOB_BY_ID_FAILURE",
  GET_JOB_BY_ID_SUCCESS: "GET_JOB_BY_ID_SUCCESS",
  CHANGE_APP_STATUS_REQUEST: "CHANGE_APP_STATUS_REQUEST",
  CHANGE_APP_STATUS_FAILURE: "CHANGE_APP_STATUS_FAILURE",
  CHANGE_APP_STATUS_SUCCESS: "CHANGE_APP_STATUS_SUCCESS",
  APPLY_ON_JOB_REQUEST: "APPLY_ON_JOB_REQUEST",
  APPLY_ON_JOB_FAILURE: "APPLY_ON_JOB_FAILURE",
  APPLY_ON_JOB_SUCCESS: "APPLY_ON_JOB_SUCCESS",
  ADD_REVIEW_REQUEST: "ADD_REVIEW_REQUEST",
  ADD_REVIEW_FAILURE: "ADD_REVIEW_FAILURE",
  ADD_REVIEW_SUCCESS: "ADD_REVIEW_SUCCESS",
};

export const postingConstants = {
  GET_POSTINGS_REQUEST: "GET_POSTINGS_REQUEST",
  GET_POSTINGS_FAILURE: "GET_POSTINGS_FAILURE",
  GET_POSTINGS_SUCCESS: "GET_POSTINGS_SUCCESS",
  POST_NEW_JOB_REQUEST: "POST_NEW_JOB_REQUEST",
  POST_NEW_JOB_FAILURE: "POST_NEW_JOB_FAILURE",
  POST_NEW_JOB_SUCCESS: "POST_NEW_JOB_SUCCESS",
};

export const applicationConstants = {
  GET_ALL_APPS_REQUEST: "GET_ALL_APPS_REQUEST",
  GET_ALL_APPS_FAILURE: "GET_ALL_APPS_FAILURE",
  GET_ALL_APPS_SUCCESS: "GET_ALL_APPS_SUCCESS",
  GET_APP_BY_ID_REQUEST: "GET_APP_BY_ID_REQUEST",
  GET_APP_BY_ID_FAILURE: "GET_APP_BY_ID_FAILURE",
  GET_APP_BY_ID_SUCCESS: "GET_APP_BY_ID_SUCCESS",
};

export const profileConstants = {
  GET_ADDRESSES_REQUEST: "GET_ADDRESSES_REQUEST",
  GET_ADDRESSES_FAILURE: "GET_ADDRESSES_FAILURE",
  GET_ADDRESSES_SUCCESS: "GET_ADDRESSES_SUCCESS",
  ADD_ADDRESS_REQUEST: "ADD_ADDRESS_REQUEST",
  ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE",
  ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
  CLEAR_ADD_ADDRESS_SUCCESS: "CLEAR_ADD_ADDRESS_SUCCESS",
};

export const searchConstants = {
  GET_SEARCH_RESULTS_REQUEST: "GET_SEARCH_RESULTS_REQUEST",
  GET_SEARCH_RESULTS_FAILURE: "GET_SEARCH_RESULTS_FAILURE",
  GET_SEARCH_RESULTS_SUCCESS: "GET_SEARCH_RESULTS_SUCCESS",
};

export const paymentConstants = {
  CREATE_PAYMENT_REQUEST: "CREATE_PAYMENT_REQUEST",
  CREATE_PAYMENT_FAILURE: "CREATE_PAYMENT_FAILURE",
  CREATE_PAYMENT_SUCCESS: "CREATE_PAYMENT_SUCCESS",
};
